# Generated by Django 4.2.10 on 2024-03-08 21:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content_management', '0001_initial'),
        ('comments', '0003_comment_updated_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='content_management.content'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='source',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='content_management.source'),
        ),
    ]
