# Generated by Django 4.2.10 on 2024-03-08 22:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='topic',
            options={'ordering': ['-created_on']},
        ),
        migrations.AddField(
            model_name='topic',
            name='created_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
