# Generated by Django 4.2.10 on 2024-03-18 21:57

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_alter_topic_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='featured_image',
            field=cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image'),
        ),
    ]
