# Generated by Django 4.2.10 on 2024-03-19 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0004_topic_featured_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='topic',
            options={'ordering': ['custom_order']},
        ),
        migrations.AddField(
            model_name='topic',
            name='custom_order',
            field=models.IntegerField(default=0),
        ),
    ]
