# Generated by Django 4.2.10 on 2024-03-07 20:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('link', models.URLField()),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('embed_code', models.TextField()),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content_management.source')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.topic')),
            ],
        ),
    ]
