# Generated by Django 4.2.10 on 2024-03-14 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='source_identifier',
            field=models.CharField(default='0', max_length=25),
        ),
        migrations.AlterField(
            model_name='content',
            name='source',
            field=models.CharField(choices=[('instagram', 'Instagram'), ('youtube', 'YouTube')], max_length=25),
        ),
        migrations.DeleteModel(
            name='Source',
        ),
    ]
