# Generated by Django 4.2.10 on 2024-03-17 08:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_alter_topic_options'),
        ('content_management', '0002_content_source_identifier_alter_content_source_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_set', to='homepage.topic'),
        ),
    ]
